TOKEN_TYPE_SINGLE_CHAR = %i(
  LEFT_PAREN RIGHT_PAREN LEFT_BRACE RIGHT_BRACE
  COMMA DOT MINUS PLUS SEMICOLON SLASH STAR
)

TOKEN_TYPE_ONE_OR_TWO_CHARS = %i(
  BANG BANG_EQUAL
  EQUAL EQUAL_EQUAL
  GREATER GREATER_EQUAL
  LESS LESS_EQUAL
)

TOKEN_TYPE_LITERALS = %i(
  IDENTIFIER STRING NUMBER
)

TOKEN_TYPE_KEYWORDS = %i(
  AND CLASS ELSE FALSE FUN FOR IF NIL OR
  PRINT RETURN SUPER THIS TRUE VAR WHILE
  EOF
)

TOKEN_TYPES = [
  TOKEN_TYPE_SINGLE_CHAR,
  TOKEN_TYPE_ONE_OR_TWO_CHARS,
  TOKEN_TYPE_LITERALS,
  TOKEN_TYPE_KEYWORDS,
].flatten.to_h { |token| [token, token.to_s] }